# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "google" {
  project     = "playground-s-11-663b4362"
  credentials = file("~/.config/gcloud/application_default_credentials.json")
  region      = "australia-southeast1"
}
