# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "my-terraform-state"
    dynamodb_table = "my-lock-table"
    encrypt        = true
    key            = "mysql/terraform.tfstate"
    region         = "us-east-1"
  }
}
